### ISSUE TITLE
Ruby 1.9.1 compatybility

### ISSUE THREAD

**Issue by andrzejsliwa** [tj/pomo#17]
Hi 

to have this working on ruby 1.9 please add this: 
# coding: utf-8

to handle correct char ''✓" in source code.

**Comment by JosephPecoraro** [comment]
Ahh, I failed to see this was a new issue. As I said in the other issue I have sent a pull request for this fix. Also, I'm surprised you didn't do it yourself (you seem pretty well versed in git!). =)

**Comment by stephenmckinney** [comment]
Fixed in 7a7aa27
