### ISSUE TITLE
Alternative notifications (with Quicksilver for example)

### ISSUE THREAD

**Issue by mocoso** [tj/pomo#23]
I've [forked this gem](https://github.com/mocoso/pomo/tree/quicksilver) to display notification messages with [Quicksilver](http://qsapp.com/).

If there is any appetite for supporting multiple notification systems then I will put together a pull request.

**Comment by sukima** [comment]
I'm on Linux so having a libnotify, XMMP (Jabber). IRC bot, and/or play a sound would be really nice.

**Comment by stephenmckinney** [comment]
Fixed in 2.0 release.
