### ISSUE TITLE
[Bug] pomo default break time is 25 min not 5 min??

### ISSUE THREAD

**Issue by zlx** [tj/pomo#36]
``` sh
config = Pomo::Configuration.load(options.__hash__)
task = Pomo::Break.new('Break time', options.__hash__)
```

``` ruby
def self.load(options = {})
   options.reject!{|k,v| ![:notifier, :progress, :tmux].include? k}
```

Because call reject! in the load method so the second `options.__hash__`  is {}, And it led to default break time to 25

I think save `options.__hash__` to one variable and use it for  `Pomo::Configuration.load` and 
`Pomo::Break.new` may solve the problem.

**Comment by stephenmckinney** [comment]
I'm on vacation currently, but will look back into it when I get back home
letter this week.

On Tuesday, February 5, 2013, zlx wrote:

> config = Pomo::Configuration.load(options.**hash**)task = Pomo::Break.new('Break time', options.**hash**)
> 
> def self.load(options = {})
>    options.reject!{|k,v| ![:notifier, :progress, :tmux].include? k}
> 
> Because call reject! in the load method so the second options.**hash** is
> {}, And it led to default break time to 25
> 
> I think save options.**hash** to one variable and use it for
> Pomo::Configuration.load and
> Pomo::Break.new may solve the problem.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/visionmedia/pomo/issues/36.

## 

-Steve
