### ISSUE TITLE
pomo ls: default to incomplete tasks?

### ISSUE THREAD

**Issue by bluestrike2** [tj/pomo#40]
Random idea, but instead of showing all tasks with `pomo ls` might it be more efficient to instead list only incomplete tasks by default then just add an `--all` option so you only get hit with everything if you explicitly want it?

I know for myself I tend to think of it as a means of seeing what's on the plate, rather than a victory lap of stuff already done (once it's done, it's pretty much behind you at that point). This'd save a few keystrokes while narrowing things down for scanning the list more efficiently. Especially if the length of your list can get a bit out of control at times.

**Comment by stephenmckinney** [comment]
I like that idea.
