### ISSUE TITLE
RVM / Archlinux issues

### ISSUE THREAD

**Issue by barraponto** [tj/pomo#42]
I've just created a gemset for pomo, but it doesn't work. Here's the output: https://gist.github.com/5215051

Steps to reproduce (on ArchLinux):

```
rvm install 1.9.3-p392
rvm use 1.9.3-p392
rvm gemset use pomo --create
gem install pomo
pomo
```

**Comment by stephenmckinney** [comment]
What's the output of `cat ~/.pomorc`?

**Comment by stephenmckinney** [comment]
Actually this is identical to #34, you have to install libnotify on Linux to use notifiers.

**Comment by barraponto** [comment]
yeah, i got confused by the "program version require" message. Anyway, shouldn't it depend on the gem libnotify?
