### ISSUE TITLE
Make tmux background color configurable

### ISSUE THREAD

**Issue by kid-icarus** [tj/pomo#44]
Right now, tmux integration uses the default bg color.

I'm using [tmux-powerline](https://github.com/erikw/tmux-powerline) which allows for tabbed segments with various colors While a pomo isn't running this looks great:
![Screen Shot 2013-04-06 at 8 07 07 PM](https://f.cloud.github.com/assets/864752/348152/e0d12d52-9f27-11e2-8b80-07862847ff20.png)

However, since a running pomo's background is hardcoded to status bar's default bg color, I can't configure the background, and it looks ugly:
![Screen Shot 2013-04-06 at 8 08 50 PM](https://f.cloud.github.com/assets/864752/348155/242982ac-9f28-11e2-9812-882912a04313.png)

**Comment by stephenmckinney** [comment]
When pomo is running we write `#[default]#[fg=green]25:00#[default]` for example to ~/.pomo_stat. I could expose some of those colors in the config file. To help me understand your context, what would that string look like in your use case?
