### ISSUE TITLE
Exception:  "program version required (Commander::Runner::CommandError)"

### ISSUE THREAD

**Issue by Gonzih** [tj/pomo#47]
Hi, just installed gem on ruby 2.0.0 and got following error:

```
~/.rvm/gems/ruby-2.0.0-p353/gems/commander-4.1.5/lib/commander/runner.rb:365:in `block in require_program': program version required (Commander::Runner::CommandError)
```

Is ruby 2.0.0 supported?

**Comment by guipdutra** [comment]
Could you please paste the complete error?

I was with the same error, and I noticed:
``require': cannot load such file -- libnotify (LoadError)`

So `gem install libnotify` solved the problem.

**Comment by Gonzih** [comment]
Yes, it helped. Thank you!

**Comment by cdown** [comment]
I'm also encountering this -- shouldn't this be an explicit dependency for pomo?

**Comment by cdown** [comment]
Oh, I guess it's because the notifier is interchangeable. We should probably still install _something_ to get a working configuration on first start.
