### ISSUE TITLE
Add hook support

### ISSUE THREAD

**Issue by tj** [tj/pomo#8]

**Comment by stephenmckinney** [comment]
Could you provide any more details on what you had in mind here?

**Comment by cgardner** [comment]
I would love to see this as well. :+1:

**Comment by tj** [comment]
kinda like git hooks

**Comment by tj** [comment]
I never remember to use pomo anymore though haha

**Comment by stephenmckinney** [comment]
I could see how this could be useful, although most of the uses I have for it (tmux refresh and notification are already baked in).

To avoid a `~/.pomo/hooks` directory, would it suffice to have one-liners in the `~/.pomorc`?:

e.g.

```
:pre-start: osascript -e 'tell application "Quicksilver" to show large type "Starting task"
:post-start: osascript -e 'tell application "Quicksilver" to show large type "Ending task"
:pre-break: osascript -e 'tell application "Quicksilver" to show large type "Starting break"
:post-break: osascript -e 'tell application "Quicksilver" to show large type "Ending break"
```

**Comment by stephenmckinney** [comment]
Closing due to lack of feedback. Will open back up if some more details come through.

**Comment by barraponto** [comment]
I'd like to tweet my pomodoros to a specific account (using t) after every pomodoro, open a redmine url in firefox (with issue number coming from task) as soon as the pomodoro starts (and ends), or run git status when pomodoro ends.
